spring:
  application:
    name: DEMO-SERVICE

server:
  port: 9095

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

      
      

       